[package]
name = "new_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quicksilver="*"
rand = "0.7.3"
nalgebra = "0.22.0"
